### ISSUE TITLE
Instructions / Linux compatibility

### ISSUE THREAD

**Issue by ob1100** [mathlucas/RDAutomation#3]
Any detailed instructions for ubuntu 20? I can run the .exe via windows but am not able to get it going via source to ubuntu 20 .

**Comment by mathlucas** [comment]
I still have to work on Linux comptatibility, shouldn't take too long. Since I host Jellyfin on Windows, I have only tested the program on this OS.

**Comment by mathlucas** [comment]
It was already kind of compatible with Linux, only you couldn't use ~/Jellyfin instead of /home/user/Jellyfin for instance, so I added os.path.expanduser to take "~" into consideration. 

Tested on Debian 12, works well, you should be fine on Ubuntu.

To use the script on Linux, you can clone the repo and execute main.py with python or python3 directly.

Commands : 
$ git clone https://github.com/mathlucas/RDAutomation
$ cd RDAutomation
$ python3 main.py

With newer versions, you might have to create a virtual environnement for python, leading to this kind of command : 
~/.venv/bin/python3 main.py

Here's the documentation in case you need it : 
https://docs.python.org/3/library/venv.html

**Comment by ob1100** [comment]
Thanks you, I am up and running now. Did not notice how new this project was.
